
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer

import webbrowser as web
from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"/Users/macbook/Desktop/vscode/py/build/assets/frame0")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()
window.title("web viewer")
window.geometry("1280x832")
window.configure(bg = "#1E1E1E")


canvas = Canvas(
    window,
    bg = "#1E1E1E",
    height = 832,
    width = 1280,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    640.0,
    41.0,
    image=image_image_1
)

image_image_2 = PhotoImage(
    file=relative_to_assets("image_2.png"))
image_2 = canvas.create_image(
    640.0,
    457.0,
    image=image_image_2
)
def search():
    value=entry_1.get()
    value=value.lower()
    if value=="youtube" :
        web.open_new('https://www.youtube.com')
    if value=="google":
         web.open('https://www.google.com')
    if value=="scratch":
         web.open('https://scratch.mit.edu')
    if value=="gmail":
         web.open('https://mail.google.com')
    if value== "one drive":
         web.open("https://onedrive.live.com")
    if value=="images":
         web.open('https://unsplash.com')   
    if value=="designes" :
         web.open('https://www.figma.com') 
    else:
       print("Sorry,Chould not able to find it.")
button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=search,
    relief="flat"
)
button_1.place(
    x=519.0,
    y=568.0,
    width=244.0,
    height=75.0
)

entry_image_1 = PhotoImage(
    file=relative_to_assets("entry_1.png"))
entry_bg_1 = canvas.create_image(
    640.0,
    199.5,
    image=entry_image_1
)
entry_1 = Entry(
    bd=0,
    bg="#000000",
    fg="#ffffff",
    highlightthickness=0
)
entry_1.place(
    x=379.0,
    y=180.0,
    width=522.0,
    height=37.0
)
window.resizable(False, False)
window.mainloop()
